[package]
name = "cad_tickers_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.20"
serde_json = "1.0.105"
ua_generator = "0.3.5"
